# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "nuget"
    directories:
    - "/QAPDashboard/"
    schedule:
      interval: "weekly"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "nuget"

  - package-ecosystem: "npm"
    directory: "/QAPDashboard/"
    schedule:
      interval: "weekly"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    pull-request-branch-name:
      separator: "-"
    target-branch: "main"
    labels:
      - "dependencies"
      - "npm"